# Generated by Django 3.2.6 on 2021-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='todolist',
            new_name='toDoList',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
